Name: firstplugin
Version: 1.0
author: noobplayer77777
main: com.noobplayer77777.firstplugin.firstplugin
api-version: 1.16
commands:
  heal:
    discription: Heals player to max health
    useage: /<command>
    aliases: healmax
